{% set version = "1.22.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-berryfunctions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/berryFunctions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/berryFunctions/berryFunctions_{{ version }}.tar.gz
  sha256: 3360bdc4c73d1d7daccc134e8b959b50bf58a67bbbf3186fc5efb5a020caa1cd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-abind
  run:
    - r-base
    - r-abind

test:
  commands:
    - $R -e "library('berryFunctions')"           # [not win]
    - "\"%R%\" -e \"library('berryFunctions')\""  # [win]

about:
  home: https://github.com/brry/berryFunctions
  license: GPL-2.0-or-later
  summary: Draw horizontal histograms, color scattered points by 3rd dimension, enhance date- and log-axis plots, zoom in X11 graphics, trace errors and warnings, use the unit hydrograph in a linear storage cascade, convert lists to data.frames and arrays, fit multiple functions.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
